# Generated by Django 5.0.7 on 2024-07-20 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre del artista:')),
                ('telefono', models.CharField(max_length=100, verbose_name='telefono del artista:')),
            ],
            options={
                'db_table': 'Artista',
            },
        ),
        migrations.CreateModel(
            name='Cancion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCa', models.CharField(max_length=100, verbose_name='Cancion:')),
                ('Fecha_Publicacion', models.DateField()),
                ('Artista', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Canciones', to='myapp.artista')),
            ],
            options={
                'db_table': 'Cancion',
            },
        ),
    ]
